# coding: utf-8
testinfo:
  title: 行车功能：MK21，一个‘-’代表一个功能
  desc: 行车功能功能具体功能操作
testcase1:
  -
    deviceMenu:
      element_info: com.spt.carengine.settings:id/menu_device_tv
      element_type: id
      element_operate: click
      operate_times: 1
testcase2:
  -
    soundAlight:
      element_info: 声音和亮度
      element_type: text
      element_operate: click
      operate_times: 1
  -
    soundSeekbar:
      element_info: //*[contains(@text, '媒体')]/../android.widget.LinearLayout/android.widget.SeekBar
      element_type: xpath
      element_operate: seekBar
      operate_times: 1

    lightSeekbar:
      element_info: //*[contains(@text, '亮度')]/../android.widget.LinearLayout/android.widget.SeekBar
      element_type: xpath
      element_operate: seekBar
      operate_times: 1
  -
    backOperate1:
      element_info:
      element_type:
      element_operate: back
      operate_times: 1
testcase3:
  -
    storage:
      element_info: 存储
      element_type: text
      element_operate: click
      operate_times: 1
  -
    backOperate1:
      element_info:
      element_type:
      element_operate: back
      operate_times: 1
testcase4:
  -
    timeAdate:
      element_info: 日期和时间
      element_type: text
      element_operate: click
      operate_times: 1
  -
    autoData:
      element_info: 自动确定日期和时间
      element_type: text
      element_operate: click
      operate_times: 1
    backOperate1:
      element_info:
      element_type:
      element_operate: back
      operate_times: 1
  -
    autotimezone:
      element_info: 自动确定时区
      element_type: text
      element_operate: click
      operate_times: 2
  -
    backOperate1:
      element_info:
      element_type:
      element_operate: back
      operate_times: 1