# coding: utf-8
testinfo:
  title: 行车功能：MK21，一个‘-’代表一个功能
  desc: 行车功能功能具体功能操作
testcase1:
  -
    systemMenu:
      element_info: com.spt.carengine.settings:id/menu_system_tv
      element_type: id
      element_operate: click
      operate_times: 1
testcase2:
  -
    systemUpdate:
      element_info: 系统更新
      element_type: text
      element_operate: click
      operate_times: 1
    updateBtn:
      element_info: com.spt.carengine.settings:id/upgrade_btn
      element_type: id
      element_operate: click
      operate_times: 1
    backOperate1:
      element_info:
      element_type:
      element_operate: back
      operate_times: 1
testcase3:
  -
    about:
      element_info: 关于本机
      element_type: text
      element_operate: click
      operate_times: 1
  -
    statInfo:
      element_info: 状态信息
      element_type: text
      element_operate: click
      operate_times: 1
    swipeElement1:
      element_info: android:id/list
      element_type: id
      element_operate: swipe_up
      operate_times: 2
    swipeElement2:
      element_info: android:id/list
      element_type: id
      element_operate: swipe_down
      operate_times: 2
    backOperate1:
      element_info:
      element_type:
      element_operate: back
      operate_times: 1
  -
    statInfo:
      element_info: 法律信息
      element_type: text
      element_operate: click
      operate_times: 1
    backOperate2:
      element_info:
      element_type:
      element_operate: back
      operate_times: 1
  -
    swipeElement1:
      element_info: android:id/list
      element_type: id
      element_operate: swipe_up
      operate_times: 2
    swipeElement2:
      element_info: android:id/list
      element_type: id
      element_operate: swipe_down
      operate_times: 2
  -
    backOperate3:
      element_info:
      element_type:
      element_operate: back
      operate_times: 1

testcase4:
  -
    reset:
      element_info: 恢复出厂设置
      element_type: text
      element_operate: click
      operate_times: 1
    reset1:
      element_info: com.android.settings:id/initiate_master_clear
      element_type: id
      element_operate: click
      operate_times: 1
  -
    backOperate3:
      element_info:
      element_type:
      element_operate: back
      operate_times: 2